In [7]:
import numpy as np

In [8]:
## create array using numpy
## create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.shape)  # shape of the array

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)

In [11]:
arr2 = np.array([1, 2, 3, 4, 5])
arr2.reshape(1, 5)  # reshape the array to 1 row and 5 columns
#print(arr2)

array([[1, 2, 3, 4, 5]])

In [10]:
print(arr2.shape)  # shape of the array

(5,)

In [12]:
##  Attributes of Numpy
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32(may vary based on platform and version)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform and version)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8

In [14]:
### Numpy Vectorized Operation
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10,20,30,40,50])

### Element Wise Addition
print("Addition:", arr1 + arr2)  

### Element Wise Subtraction
print("Subtraction:", arr1 - arr2)  

### Element Wise Multiplication
print("Multiplication:", arr1 * arr2)

### Element Wise Division

Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]

### Universal Functions - (UFuncs)

In [15]:
## Universal Functions
arr = np.array([2,3,4,5,6])

## square root
print(np.sqrt(arr))  

## Exponential
print(np.exp(arr))  

## Sine 
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]

In [16]:
## array slicing and indexing
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Arrayy:\n", arr)

Arrayy:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

In [18]:
print(arr[0][0])
print(arr[0:2,1:])
print(arr[1:,2:])

1
[[2 3]
 [5 6]]
[[6]
 [9]]

In [21]:
import pandas as pd
data = [1, 2, 3, 4, 5]
series = pd.Series(data)
print("Series:\n", series)
print(type(series))

Series:
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [27]:
## Create a series from  dictionary
data = {'a': 1, 'b': 2, 'c': 3}
series_dict = pd.Series(data)
print(series_dict)
print(type(series_dict))

a    1
b    2
c    3
dtype: int64
<class 'pandas.core.series.Series'>

In [23]:
data = [10, 20, 30]
index = ['a', 'b', 'c']
pd.Series(data, index=index)

a    10
b    20
c    30
dtype: int64

In [25]:
## DataFrame
## Create a DataFrame from a dictionary
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}
df = pd.DataFrame(data)
print("DataFrame:\n", df)
print(type(df))

DataFrame:
       Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
<class 'pandas.core.frame.DataFrame'>

In [28]:
## Create a DataFrame from a list of Dictionaries
data = [
    {'Name': 'Alice', 'Age': 25, 'City': 'New York'},
    {'Name': 'Bob', 'Age': 30, 'City': 'Los Angeles'},
    {'Name': 'Charlie', 'Age': 35, 'City': 'Chicago'}
]
df_list = pd.DataFrame(data)
print("DataFrame from list of dictionaries:\n", df_list)
print(type(df_list))

DataFrame from list of dictionaries:
       Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
<class 'pandas.core.frame.DataFrame'>

In [29]:
df = pd.read_csv('sales_data.csv')
print(df.head(5))

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [30]:
df.tail(5)  # last 5 rows

          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [31]:
df

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    NaN   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    NaN  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    NaN  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    NaN  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    NaN   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    NaN   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    NaN  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [32]:
df['Date']

0     2023-01-01
1     2023-01-02
2     2023-01-03
3     2023-01-04
4     2023-01-05
5     2023-01-06
6     2023-01-07
7     2023-01-08
8     2023-01-09
9     2023-01-10
10    2023-01-11
11    2023-01-12
12    2023-01-13
13    2023-01-14
14    2023-01-15
15    2023-01-16
16    2023-01-17
17    2023-01-18
18    2023-01-19
19    2023-01-20
20    2023-01-21
21    2023-01-22
22    2023-01-23
23    2023-01-24
24    2023-01-25
25    2023-01-26
26    2023-01-27
27    2023-01-28
28    2023-01-29
29    2023-01-30
30    2023-01-31
31    2023-02-01
32    2023-02-02
33    2023-02-03
34    2023-02-04
35    2023-02-05
36    2023-02-06
37    2023-02-07
38    2023-02-08
39    2023-02-09
40    2023-02-10
41    2023-02-11
42    2023-02-12
43    2023-02-13
44    2023-02-14
45    2023-02-15
46    2023-02-16
47    2023-02-17
48    2023-02-18
49    2023-02-19
Name: Date, dtype: object

In [ ]:
df.loc[0][0]

/var/folders/vv/zbbdr6kj08zbndtvzhfmfjnc0000gn/T/ipykernel_50023/2527876973.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][0]

'2023-01-01'

In [35]:
## Accessing specified element
df.at[1,'Region']

'North'

In [37]:
## Adding a column with a default value
df['Salary'] = [1000] * len(df)  # Assigning a default value of 1000 to all rows
df

          Date Category  Value   Product  Sales Region  Salary
0   2023-01-01        A   28.0  Product1  754.0   East    1000
1   2023-01-02        B   39.0  Product3  110.0  North    1000
2   2023-01-03        C   32.0  Product2  398.0   East    1000
3   2023-01-04        B    8.0  Product1  522.0   East    1000
4   2023-01-05        B   26.0  Product3  869.0  North    1000
5   2023-01-06        B   54.0  Product3  192.0   West    1000
6   2023-01-07        A   16.0  Product1  936.0   East    1000
7   2023-01-08        C   89.0  Product1  488.0   West    1000
8   2023-01-09        C   37.0  Product3  772.0   West    1000
9   2023-01-10        A   22.0  Product2  834.0   West    1000
10  2023-01-11        B    7.0  Product1  842.0  North    1000
11  2023-01-12        B   60.0  Product2    NaN   West    1000
12  2023-01-13        A   70.0  Product3  628.0  South    1000
13  2023-01-14        A   69.0  Product1  423.0   East    1000
14  2023-01-15        A   47.0  Product2  893.0   West    1000
15  2023-01-16        C    NaN  Product1  895.0  North    1000
16  2023-01-17        C   93.0  Product2  511.0  South    1000
17  2023-01-18        C    NaN  Product1  108.0   West    1000
18  2023-01-19        A   31.0  Product2  578.0   West    1000
19  2023-01-20        A   59.0  Product1  736.0   East    1000
20  2023-01-21        C   82.0  Product3  606.0  South    1000
21  2023-01-22        C   37.0  Product2  992.0  South    1000
22  2023-01-23        B   62.0  Product3  942.0  North    1000
23  2023-01-24        C   92.0  Product2  342.0   West    1000
24  2023-01-25        A   24.0  Product2  458.0   East    1000
25  2023-01-26        C   95.0  Product1  584.0   West    1000
26  2023-01-27        C   71.0  Product2  619.0  North    1000
27  2023-01-28        C   56.0  Product2  224.0  North    1000
28  2023-01-29        B    NaN  Product3  617.0  North    1000
29  2023-01-30        C   51.0  Product2  737.0  South    1000
30  2023-01-31        B   50.0  Product3  735.0   West    1000
31  2023-02-01        A   17.0  Product2  189.0   West    1000
32  2023-02-02        B   63.0  Product3  338.0  South    1000
33  2023-02-03        C   27.0  Product3    NaN   East    1000
34  2023-02-04        C   70.0  Product3  669.0   West    1000
35  2023-02-05        B   60.0  Product2    NaN   West    1000
36  2023-02-06        C   36.0  Product3  177.0   East    1000
37  2023-02-07        C    2.0  Product1    NaN  North    1000
38  2023-02-08        C   94.0  Product1  408.0  South    1000
39  2023-02-09        A   62.0  Product1  155.0   West    1000
40  2023-02-10        B   15.0  Product1  578.0   East    1000
41  2023-02-11        C   97.0  Product1  256.0   East    1000
42  2023-02-12        A   93.0  Product3  164.0   West    1000
43  2023-02-13        A   43.0  Product3  949.0   East    1000
44  2023-02-14        A   96.0  Product3  830.0   East    1000
45  2023-02-15        B   99.0  Product2  599.0   West    1000
46  2023-02-16        B    6.0  Product1  938.0  South    1000
47  2023-02-17        B   69.0  Product3  143.0   West    1000
48  2023-02-18        C   65.0  Product3  182.0  North    1000
49  2023-02-19        C   11.0  Product3  708.0  North    1000

In [38]:
## Remove a column 
df.drop('Salary', axis=1, inplace=True)  # Remove the 'Salary' column

In [39]:
df

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    NaN   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    NaN  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    NaN  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    NaN  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    NaN   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    NaN   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    NaN  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [40]:
## Add +1 to all values in the 'Sales' column
df['Sales'] = df['Sales'] + 1
df

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  755.0   East
1   2023-01-02        B   39.0  Product3  111.0  North
2   2023-01-03        C   32.0  Product2  399.0   East
3   2023-01-04        B    8.0  Product1  523.0   East
4   2023-01-05        B   26.0  Product3  870.0  North
5   2023-01-06        B   54.0  Product3  193.0   West
6   2023-01-07        A   16.0  Product1  937.0   East
7   2023-01-08        C   89.0  Product1  489.0   West
8   2023-01-09        C   37.0  Product3  773.0   West
9   2023-01-10        A   22.0  Product2  835.0   West
10  2023-01-11        B    7.0  Product1  843.0  North
11  2023-01-12        B   60.0  Product2    NaN   West
12  2023-01-13        A   70.0  Product3  629.0  South
13  2023-01-14        A   69.0  Product1  424.0   East
14  2023-01-15        A   47.0  Product2  894.0   West
15  2023-01-16        C    NaN  Product1  896.0  North
16  2023-01-17        C   93.0  Product2  512.0  South
17  2023-01-18        C    NaN  Product1  109.0   West
18  2023-01-19        A   31.0  Product2  579.0   West
19  2023-01-20        A   59.0  Product1  737.0   East
20  2023-01-21        C   82.0  Product3  607.0  South
21  2023-01-22        C   37.0  Product2  993.0  South
22  2023-01-23        B   62.0  Product3  943.0  North
23  2023-01-24        C   92.0  Product2  343.0   West
24  2023-01-25        A   24.0  Product2  459.0   East
25  2023-01-26        C   95.0  Product1  585.0   West
26  2023-01-27        C   71.0  Product2  620.0  North
27  2023-01-28        C   56.0  Product2  225.0  North
28  2023-01-29        B    NaN  Product3  618.0  North
29  2023-01-30        C   51.0  Product2  738.0  South
30  2023-01-31        B   50.0  Product3  736.0   West
31  2023-02-01        A   17.0  Product2  190.0   West
32  2023-02-02        B   63.0  Product3  339.0  South
33  2023-02-03        C   27.0  Product3    NaN   East
34  2023-02-04        C   70.0  Product3  670.0   West
35  2023-02-05        B   60.0  Product2    NaN   West
36  2023-02-06        C   36.0  Product3  178.0   East
37  2023-02-07        C    2.0  Product1    NaN  North
38  2023-02-08        C   94.0  Product1  409.0  South
39  2023-02-09        A   62.0  Product1  156.0   West
40  2023-02-10        B   15.0  Product1  579.0   East
41  2023-02-11        C   97.0  Product1  257.0   East
42  2023-02-12        A   93.0  Product3  165.0   West
43  2023-02-13        A   43.0  Product3  950.0   East
44  2023-02-14        A   96.0  Product3  831.0   East
45  2023-02-15        B   99.0  Product2  600.0   West
46  2023-02-16        B    6.0  Product1  939.0  South
47  2023-02-17        B   69.0  Product3  144.0   West
48  2023-02-18        C   65.0  Product3  183.0  North
49  2023-02-19        C   11.0  Product3  709.0  North

In [41]:
df.describe()  # statistical summary of the DataFrame

           Value       Sales
count  47.000000   46.000000
mean   51.744681  558.130435
std    29.050532  274.598584
min     2.000000  109.000000
25%    27.500000  340.000000
50%    54.000000  592.500000
75%    70.000000  768.500000
max    99.000000  993.000000

In [44]:
# Handling missing values
df.isnull().any(axis=1)  # rows with missing values

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14    False
15     True
16    False
17     True
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28     True
29    False
30    False
31    False
32    False
33     True
34    False
35     True
36    False
37     True
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
dtype: bool

In [45]:
df.isnull().sum()  # count of missing values in each column

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [46]:
#filling missing values with the mean of the column
df['Sales_fillNA'] = df['Sales'].fillna(df['Sales'].mean())
df

          Date Category  Value   Product  Sales Region  Sales_fillNA
0   2023-01-01        A   28.0  Product1  755.0   East    755.000000
1   2023-01-02        B   39.0  Product3  111.0  North    111.000000
2   2023-01-03        C   32.0  Product2  399.0   East    399.000000
3   2023-01-04        B    8.0  Product1  523.0   East    523.000000
4   2023-01-05        B   26.0  Product3  870.0  North    870.000000
5   2023-01-06        B   54.0  Product3  193.0   West    193.000000
6   2023-01-07        A   16.0  Product1  937.0   East    937.000000
7   2023-01-08        C   89.0  Product1  489.0   West    489.000000
8   2023-01-09        C   37.0  Product3  773.0   West    773.000000
9   2023-01-10        A   22.0  Product2  835.0   West    835.000000
10  2023-01-11        B    7.0  Product1  843.0  North    843.000000
11  2023-01-12        B   60.0  Product2    NaN   West    558.130435
12  2023-01-13        A   70.0  Product3  629.0  South    629.000000
13  2023-01-14        A   69.0  Product1  424.0   East    424.000000
14  2023-01-15        A   47.0  Product2  894.0   West    894.000000
15  2023-01-16        C    NaN  Product1  896.0  North    896.000000
16  2023-01-17        C   93.0  Product2  512.0  South    512.000000
17  2023-01-18        C    NaN  Product1  109.0   West    109.000000
18  2023-01-19        A   31.0  Product2  579.0   West    579.000000
19  2023-01-20        A   59.0  Product1  737.0   East    737.000000
20  2023-01-21        C   82.0  Product3  607.0  South    607.000000
21  2023-01-22        C   37.0  Product2  993.0  South    993.000000
22  2023-01-23        B   62.0  Product3  943.0  North    943.000000
23  2023-01-24        C   92.0  Product2  343.0   West    343.000000
24  2023-01-25        A   24.0  Product2  459.0   East    459.000000
25  2023-01-26        C   95.0  Product1  585.0   West    585.000000
26  2023-01-27        C   71.0  Product2  620.0  North    620.000000
27  2023-01-28        C   56.0  Product2  225.0  North    225.000000
28  2023-01-29        B    NaN  Product3  618.0  North    618.000000
29  2023-01-30        C   51.0  Product2  738.0  South    738.000000
30  2023-01-31        B   50.0  Product3  736.0   West    736.000000
31  2023-02-01        A   17.0  Product2  190.0   West    190.000000
32  2023-02-02        B   63.0  Product3  339.0  South    339.000000
33  2023-02-03        C   27.0  Product3    NaN   East    558.130435
34  2023-02-04        C   70.0  Product3  670.0   West    670.000000
35  2023-02-05        B   60.0  Product2    NaN   West    558.130435
36  2023-02-06        C   36.0  Product3  178.0   East    178.000000
37  2023-02-07        C    2.0  Product1    NaN  North    558.130435
38  2023-02-08        C   94.0  Product1  409.0  South    409.000000
39  2023-02-09        A   62.0  Product1  156.0   West    156.000000
40  2023-02-10        B   15.0  Product1  579.0   East    579.000000
41  2023-02-11        C   97.0  Product1  257.0   East    257.000000
42  2023-02-12        A   93.0  Product3  165.0   West    165.000000
43  2023-02-13        A   43.0  Product3  950.0   East    950.000000
44  2023-02-14        A   96.0  Product3  831.0   East    831.000000
45  2023-02-15        B   99.0  Product2  600.0   West    600.000000
46  2023-02-16        B    6.0  Product1  939.0  South    939.000000
47  2023-02-17        B   69.0  Product3  144.0   West    144.000000
48  2023-02-18        C   65.0  Product3  183.0  North    183.000000
49  2023-02-19        C   11.0  Product3  709.0  North    709.000000

In [47]:
df.dtypes

Date             object
Category         object
Value           float64
Product          object
Sales           float64
Region           object
Sales_fillNA    float64
dtype: object

In [48]:
## Renaming Columns
df = df.rename(columns ={'Date':'Sales Date'})

In [49]:
df.head()

   Sales Date Category  Value   Product  Sales Region  Sales_fillNA
0  2023-01-01        A   28.0  Product1  755.0   East         755.0
1  2023-01-02        B   39.0  Product3  111.0  North         111.0
2  2023-01-03        C   32.0  Product2  399.0   East         399.0
3  2023-01-04        B    8.0  Product1  523.0   East         523.0
4  2023-01-05        B   26.0  Product3  870.0  North         870.0

In [51]:
## change datatypes
df['Value'] = df['Value'].fillna(df['Value'].mean())
df['Value_new'] = df['Value'].astype('int')
df.head()

   Sales Date Category  Value   Product  Sales Region  Sales_fillNA  Value_new
0  2023-01-01        A   28.0  Product1  755.0   East         755.0         28
1  2023-01-02        B   39.0  Product3  111.0  North         111.0         39
2  2023-01-03        C   32.0  Product2  399.0   East         399.0         32
3  2023-01-04        B    8.0  Product1  523.0   East         523.0          8
4  2023-01-05        B   26.0  Product3  870.0  North         870.0         26

In [53]:
df['New Value'] = df['Value'].apply(lambda x: x * 2)
df.head()

,Sales Date,Category,Value,Product,Sales,Region,Sales_fillNA,Value_new,New Value
0,2023-01-01,A,28.0,Product1,755.0,East,755.0,28,56.0
1,2023-01-02,B,39.0,Product3,111.0,North,111.0,39,78.0
2,2023-01-03,C,32.0,Product2,399.0,East,399.0,32,64.0
3,2023-01-04,B,8.0,Product1,523.0,East,523.0,8,16.0
4,2023-01-05,B,26.0,Product3,870.0,North,870.0,26,52.0

In [54]:
## Data Aggregation and Grouping
grouped_mean= df.groupby('Product')['Value'].mean()
print(grouped_mean)

Product
Product1    46.905585
Product2    52.800000
Product3    54.986562
Name: Value, dtype: float64

In [55]:
grouped_sum = df.groupby(['Product', 'Region'])['Value'].sum()
print(grouped_sum)

Product   Region
Product1  East      292.000000
          North      60.744681
          South     100.000000
          West      297.744681
Product2  East       56.000000
          North     127.000000
          South     181.000000
          West      428.000000
Product3  East      202.000000
          North     254.744681
          South     215.000000
          West      373.000000
Name: Value, dtype: float64

In [57]:
## aggreagte with multiple functions
grouped_agg = df.groupby('Region')['Value'].agg(['mean', 'sum', 'count'])
print(grouped_agg)

             mean          sum  count
Region
East    42.307692   550.000000     13
North   40.226306   442.489362     11
South   62.000000   496.000000      8
West    61.041371  1098.744681     18

In [58]:
## Merging and joining Dataframes
# Create a sample DataFrame
df1 = pd.DataFrame({
    'Key' : ['A', 'B', 'C'],
    'Value1' : [1, 2, 3]
})
df2 = pd.DataFrame({
    'Key' : ['A', 'B', 'D'],
    'Value2' : [4, 5, 6]
})

In [60]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [61]:
df2

  Key  Value2
0   A       4
1   B       5
2   D       6

In [62]:
## Merge Dateframe on the 'Key Columns'
pd.merge(df1, df2, on='Key', how='inner')  # Inner join

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [ ]:
pd.merge(df1, df2, on='Key', how='outer')  # out join

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [64]:
pd.merge(df1, df2, on='Key', how='left')  # left join

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [71]:
import pandas as pd
from io import StringIO
# Alternative approach with single quotes outside and double quotes inside
Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr.Developer"}]}'

In [72]:
df = pd.read_json(StringIO(Data))
df

,employee_name,email,job_profile
0,James,james@gmail.com,"{'title1': 'Team Lead', 'title2': 'Sr.Developer'}"

In [73]:
df.to_json()

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team Lead","title2":"Sr.Developer"}}}'

In [74]:
df.to_json(orient='index')

'{"0":{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr.Developer"}}}'

In [76]:
df.to_json(orient='records')  # Convert to JSON with records orientation

'[{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr.Developer"}}]'

In [78]:
df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",header=None)

In [79]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [80]:
df.to_csv('wine.csv')  # Save DataFrame to CSV file

In [81]:
!pip install lxml
!pip install html5lib
!pip install beautifulsoup4

Collecting lxml
  Downloading lxml-5.4.0-cp311-cp311-macosx_10_9_universal2.whl.metadata (3.5 kB)
Downloading lxml-5.4.0-cp311-cp311-macosx_10_9_universal2.whl (8.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 56.6 MB/s eta 0:00:00
Installing collected packages: lxml
Successfully installed lxml-5.4.0

[notice] A new release of pip is available: 24.2 -> 25.1.1
[notice] To update, run: pip install --upgrade pip
Collecting html5lib
  Downloading html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: six>=1.9 in /Users/fahdmohammed/Desktop/workspace/da-2024/env/lib/python3.11/site-packages (from html5lib) (1.16.0)
Collecting webencodings (from html5lib)
  Downloading webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Installing collected packages: webencodings, html5lib
Successfully installed html5lib-1.1 webencodings-0.5.1

[notice] A new release of pip is available: 24.2 -> 25.1.1
[notice] To update, run: pip install --upgrade pip
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.13.4-py3-none-any.whl.metadata (3.8 kB)
Collecting soupsieve>1.2 (from beautifulsoup4)
  Downloading soupsieve-2.7-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in /Users/fahdmohammed/Desktop/workspace/da-2024/env/lib/python3.11/site-packages (from beautifulsoup4) (4.12.2)
Downloading beautifulsoup4-4.13.4-py3-none-any.whl (187 kB)
Downloading soupsieve-2.7-py3-none-any.whl (36 kB)
Installing collected packages: soupsieve, beautifulsoup4
Successfully installed beautifulsoup4-4.13.4 soupsieve-2.7

[notice] A new release of pip is available: 24.2 -> 25.1.1
[notice] To update, run: pip install --upgrade pip

In [83]:
url="https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/"

df = pd.read_html(url)

In [85]:
df

[                               Bank Name               City         State  \
 0                   Pulaski Savings Bank            Chicago      Illinois
 1     The First National Bank of Lindsay            Lindsay      Oklahoma
 2  Republic First Bank dba Republic Bank       Philadelphia  Pennsylvania
 3                          Citizens Bank           Sac City          Iowa
 4               Heartland Tri-State Bank            Elkhart        Kansas
 5                    First Republic Bank      San Francisco    California
 6                         Signature Bank           New York      New York
 7                    Silicon Valley Bank        Santa Clara    California
 8                      Almena State Bank             Almena        Kansas
 9             First City Bank of Florida  Fort Walton Beach       Florida

     Cert                Acquiring Institution      Closing Date  \
 0  28611                      Millennium Bank  January 17, 2025
 1   4134   First Bank & Trust Co., Duncan, OK  October 18, 2024
 2  27332    Fulton Bank, National Association    April 26, 2024
 3   8758            Iowa Trust & Savings Bank  November 3, 2023
 4  25851               Dream First Bank, N.A.     July 28, 2023
 5  59017            JPMorgan Chase Bank, N.A.       May 1, 2023
 6  57053                  Flagstar Bank, N.A.    March 12, 2023
 7  24735  First Citizens Bank & Trust Company    March 10, 2023
 8  15426                          Equity Bank  October 23, 2020
 9  16748            United Fidelity Bank, fsb  October 16, 2020

    Fund  Sort ascending
 0                 10548
 1                 10547
 2                 10546
 3                 10545
 4                 10544
 5                 10543
 6                 10540
 7                 10539
 8                 10538
 9                 10537  ]

In [88]:
url = "https://en.wikipedia.org/wiki/Mobile_country_code"
pd.read_html(url, match="Country", header=0)[0]  # Read the first table with "Country" in the header

,Mobile country code,Country,ISO 3166,Mobile network codes,National MNC authority,Remarks
0,289,A Abkhazia,GE-AB,List of mobile network codes in Abkhazia,NaN,MCC is not listed by ITU
1,412,Afghanistan,AF,List of mobile network codes in Afghanistan,NaN,NaN
2,276,Albania,AL,List of mobile network codes in Albania,NaN,NaN
3,603,Algeria,DZ,List of mobile network codes in Algeria,NaN,NaN
4,544,American Samoa (United States of America),AS,List of mobile network codes in American Samoa,NaN,NaN
...,...,...,...,...,...,...
247,452,Vietnam,VN,List of mobile network codes in the Vietnam,NaN,NaN
248,543,W Wallis and Futuna,WF,List of mobile network codes in Wallis and Futuna,NaN,NaN
249,421,Y Yemen,YE,List of mobile network codes in the Yemen,NaN,NaN
250,645,Z Zambia,ZM,List of mobile network codes in Zambia,NaN,NaN
251,648,Zimbabwe,ZW,List of mobile network codes in Zimbabwe,NaN,NaN

In [89]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /Users/fahdmohammed/Desktop/workspace/da-2024/env/lib/python3.11/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /Users/fahdmohammed/Desktop/workspace/da-2024/env/lib/python3.11/site-packages (from openpyxl) (1.1.0)

[notice] A new release of pip is available: 24.2 -> 25.1.1
[notice] To update, run: pip install --upgrade pip

In [91]:
df_excel = pd.read_excel('data.xlsx')  # Read a specific sheet from an Excel file

ValueError: Excel file format cannot be determined, you must specify an engine manually.